// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8HuygLbbNK3QG4o5W5EVQ0D9J3mBb9QE',
    appId: '1:1059405127167:web:e2d395fdf30334e12f9bca',
    messagingSenderId: '1059405127167',
    projectId: 'ironpulse-2ca24',
    authDomain: 'ironpulse-2ca24.firebaseapp.com',
    storageBucket: 'ironpulse-2ca24.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAjy-Dy96k5AvPaO7g6xe77WpRWNsl9lU',
    appId: '1:1059405127167:android:9192b8c4982e13f42f9bca',
    messagingSenderId: '1059405127167',
    projectId: 'ironpulse-2ca24',
    storageBucket: 'ironpulse-2ca24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAugK4rsANvM3F4u-Fgs_KUy0tCahzf4po',
    appId: '1:1059405127167:ios:5bb66746ee3583382f9bca',
    messagingSenderId: '1059405127167',
    projectId: 'ironpulse-2ca24',
    storageBucket: 'ironpulse-2ca24.firebasestorage.app',
    iosBundleId: 'com.example.ironPulse',
  );
}
